name: Signaler un bug
description: Vous avez rencontré un bug? Signalez-le ici
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
     value: |
      Yardımın için çok teşekkür ederim.Ancak, bize yardımcı olacak bir dizi bilgiye ihtiyacımız var.
  - type: checkboxes
    attributes:
      label: "Hata raporunun açılışını doğrulamadan önce yapılacak çeklerin listesi"
      description: Raporunuz reddedilebilirse, aşağıdakileri tamamladığınızdan emin olun
      options:
        - label: Selvania fırlatıcısındaki hatayı yeniden üretmeyi başardım (değişikliklerim olmadan)
          required: true
        - label: Pzt Code Saygı La Lisans Creative Commons Zero V1.0 Universal
          required: true
        - label: Kodum Selvania başlatıcısının kullanım koşullarına uygun
          required: true
        - label: Royalnetwork Launcher'ın en son sürümünde hatayı yeniden üretmeyi başardım
          required: true
  - type: dropdown
    attributes:
      label: İşletim sistemi
      options:
        - Windows
        - macOS
        - Linux (Debian/Ubuntu'ya dayanarak)
        - Linux (Diğerleri)
    validations:
      required: true
  - type: input
    attributes:
      label: İşletim sistemi sürümü
      placeholder: "Örnek: Windows 11 Profesyonel 9: 14:00 22000.739"
    validations:
        required: true
  - type: input
    attributes:
      label: Hatanın karşılaştığı karma iş
      placeholder: 84d7881b67ecf6088205eca6723bfb19bf2a5f0d
  - type: textarea
    attributes:
      label: Beklenen davranış
      description: Ne olması gerektiğinin bir açıklaması
      placeholder: Başlatıcı olmalı ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Mevcut davranış
      description: Hatada neler olup bittiğinin bir açıklaması
    validations:
      required: true
  - type: textarea
    attributes:
      label: Hedefi yeniden üretme talimatları
      placeholder: |
        1. Başlatıcıyı aç
        2. XYZ menüsüne git
        3. ABC'ye tıklayın
        4. Observer
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ek Notlar
      placeholder: Hata ile ilgili ek ayrıntılar, yararlı olabilecek her şey
    validations:
      required: false
