blank_issues_enabled: false
contact_links:
  - name: Herhangi bir soru veya istek için anlaşmazlık konusunda bize katılın
    url: https://discord.gg/ex7ZATCvpu
    about: Lütfen hataları bildirmekten başka bir yol açmayın
